MODEL:
  TYPE: vssm
  NAME: vssm1_base
  DROP_PATH_RATE: 0.6
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 16, 2 ]
    D_STATE: 16
    DT_RANK: "auto"
    SSM_RATIO: 1.6
    MLP_RATIO: 2.0

# 69M + 14.6G + 27min

