MODEL:
  TYPE: vssm
  NAME: vssm1_tiny
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 4, 2 ]
    D_STATE: 16
    DT_RANK: "auto"
    SSM_RATIO: 1.6
    MLP_RATIO: 2.0
    # DOWNSAMPLE: "v1"

# 21M + 4.45G + 12.5min
